In [1]:
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 2.0000e+00, 0.0000e+00],
        [2.0000e+00, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.3114, 0.5470, 0.9157],
        [0.6518, 0.7896, 0.5755],
        [0.5513, 0.2412, 0.5975],
        [0.0446, 0.4766, 0.2279],
        [0.4234, 0.3180, 0.5658]])


In [4]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x.size()

torch.Size([5, 3])

In [6]:
x.shape

torch.Size([5, 3])

In [7]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x.size()

torch.Size([2])

In [9]:
x.shape

torch.Size([2])

In [10]:
y = torch.rand(1, 2)
print(y)

tensor([[0.3715, 0.9625]])


In [11]:
# Addition: 1
print(x + y)

tensor([[5.8715, 3.9625]])


In [12]:
# Addition: 2
print(torch.add(x, y))

tensor([[5.8715, 3.9625]])


In [13]:
# Addition: 3
result = torch.empty(1, 2)
print(torch.add(x, y, out=result))

tensor([[5.8715, 3.9625]])


In [14]:
print(result)

tensor([[5.8715, 3.9625]])


In [15]:
# Addition: 4
print(y.add_(x))

tensor([[5.8715, 3.9625]])


In [16]:
print(x[1])

tensor(3.)


In [17]:
# Resize/reshape tensor
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# Get the value as a Python numbe
x = torch.rand(1)
print(x.size())
print(x.item())

torch.Size([1])
0.4506874680519104


In [19]:
# Convert Torch tensor to Numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
print(a.add_(1))
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
a

tensor([2., 2., 2., 2., 2.])

In [22]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [23]:
# Convert Numpy array to Torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
a

array([2., 2., 2., 2., 2.])

In [25]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [26]:
# CUDA tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    # Directly create a tensor on GPU
    y = torch.ones_like(x, device=device)
    
    # Move onto any device using the .to method
    x = x.to(device)
    
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))