In [1]:
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45]])


In [4]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.6325, 0.3922, 0.9664],
        [0.7593, 0.3153, 0.7069],
        [0.3206, 0.6110, 0.2826],
        [0.3333, 0.4057, 0.4198],
        [0.6264, 0.2511, 0.9433]])


In [10]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x.size()

torch.Size([5, 3])

In [13]:
x.shape

torch.Size([5, 3])

In [15]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x.size()

torch.Size([2])

In [16]:
x.shape

torch.Size([2])

In [18]:
y = torch.rand(1, 2)
print(y)

tensor([[0.6683, 0.2811]])


In [19]:
# Addition: 1
print(x + y)

tensor([[6.1683, 3.2811]])


In [20]:
# Addition: 2
print(torch.add(x, y))

tensor([[6.1683, 3.2811]])


In [21]:
# Addition: 3
result = torch.empty(1, 2)
print(torch.add(x, y, out=result))

tensor([[6.1683, 3.2811]])


In [22]:
print(result)

tensor([[6.1683, 3.2811]])


In [23]:
# Addition: 4
print(y.add_(x))

tensor([[6.1683, 3.2811]])


In [26]:
print(x[1])

tensor(3.)


In [28]:
# Resize/reshape tensor
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
# Get the value as a Python numbe
x = torch.rand(1)
print(x.size())
print(x.item())

torch.Size([1])
0.6804080605506897


In [31]:
# Convert Torch tensor to Numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [32]:
print(a.add_(1))
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
a

tensor([2., 2., 2., 2., 2.])

In [35]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [38]:
# Convert Numpy array to Torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [39]:
a

array([1., 1., 1., 1., 1.])

In [40]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [42]:
# CUDA tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    # Directly create a tensor on GPU
    y = torch.ones_like(x, device=device)
    
    # Move onto any device using the .to method
    x = x.to(device)
    
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))